language: node

script:
  - npm run build

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: pages
  local-dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
